"""Negotiate Module: drafts personalized partnership pitches and delivers them via email.

Pipeline position: Stage 2 of 3
Input:  companies with status='scouted' that have a contact_email
Output: outbound emails via Resend, companies updated to status='pitched'

Design notes:
- Claude sonnet writes the copy — better quality than haiku for creative tasks.
- Both subject line AND body are generated by the LLM in a single call (one JSON object).
- Exponential back-off on API calls; failures skip the lead without aborting the run.
- EMAIL_RATE_LIMIT_SECONDS paces sends to avoid hitting Resend rate limits.
- DRY_RUN=true (the default) prints emails but never delivers them — safe for testing.
- email_subject and email_body are stored in the DB for audit and follow-up tracking.
"""

import json
import time
from dotenv import load_dotenv
import resend
import anthropic

from config import Config
from db import get_connection
from logger import get_logger

load_dotenv()
log = get_logger("negotiate")

_SYSTEM_PROMPT = (
    "You are the Head of Partnerships at Symbiote AI, an autonomous business development platform. "
    "Your outreach style is casual, direct, and founder-to-founder. "
    "Write at a 6th-grade reading level. "
    "Never use corporate buzzwords (synergy, leverage, unlock, game-changing, revolutionary, delve). "
    "STRICT RULE: Never mention money, compensation, equity, or revenue share of any kind. "
    "We offer only audience exposure — a 1-to-1 swap."
)


def _draft_email(
    client: anthropic.Anthropic,
    company_name: str,
    url: str,
    context_notes: str,
    retries: int = 3,
) -> tuple[str, str]:
    """Generate a (subject, body) pair for a cold outreach email.

    Falls back to a hardcoded template if the LLM call fails after all retries.
    """
    prompt = (
        f"Write a cold outreach email to '{company_name}' ({url}) proposing a 1-to-1 audience swap "
        f"(newsletter cross-promotion or widget placement). No financial compensation, ever.\n\n"
        f"Context about them: {context_notes}\n\n"
        f"Rules:\n"
        f"- Subject: casual, specific, under 60 chars, no emojis\n"
        f"- Body: exactly 3 sentences\n"
        f"  Sentence 1 — personalized hook: prove you read their site\n"
        f"  Sentence 2 — shared audience + mutual benefit of the swap\n"
        f"  Sentence 3 — casual CTA, e.g. 'Open to a quick audience swap?'\n"
        f"- Sign off as: {Config.SENDER_NAME}\n\n"
        f'Respond ONLY with JSON: {{"subject": "...", "body": "..."}}'
    )

    for attempt in range(retries):
        try:
            response = client.messages.create(
                model=Config.SMART_MODEL,
                max_tokens=512,
                system=_SYSTEM_PROMPT,
                messages=[{"role": "user", "content": prompt}],
            )
            raw = response.content[0].text.strip()
            # Strip markdown fences if the model adds them
            if raw.startswith("```"):
                parts = raw.split("```")
                raw = parts[1]
                if raw.startswith("json"):
                    raw = raw[4:]
            data = json.loads(raw.strip())
            subject = data.get("subject") or f"Partnership idea: Symbiote AI x {company_name}"
            body = data.get("body") or ""
            if subject and body:
                return subject, body

        except json.JSONDecodeError as e:
            log.warning(f"JSON parse error drafting email for {company_name} (attempt {attempt + 1}): {e}")
            return _fallback_email(company_name, url)  # deterministic; no point retrying

        except anthropic.APIStatusError as e:
            wait = 2 ** attempt
            log.warning(
                f"Anthropic API error {e.status_code} for {company_name} "
                f"(attempt {attempt + 1}/{retries}). Retrying in {wait}s."
            )
            time.sleep(wait)

        except anthropic.APIConnectionError as e:
            wait = 2 ** attempt
            log.warning(f"Connection error (attempt {attempt + 1}/{retries}): {e}. Retrying in {wait}s.")
            time.sleep(wait)

    log.warning(f"All retries exhausted for {company_name}. Using fallback email.")
    return _fallback_email(company_name, url)


def _fallback_email(company_name: str, url: str) -> tuple[str, str]:
    subject = f"Quick audience swap idea — {company_name}?"
    body = (
        f"Hey {company_name}, loved what you're building at {url} and think our audiences overlap. "
        f"We're Symbiote AI, and we'd love to explore a 1-to-1 newsletter cross-promotion — "
        f"pure exposure swap, nothing more. Open to a quick audience swap?"
    )
    return subject, body


def draft_and_send_emails(dry_run: bool | None = None) -> int:
    """Draft and send outreach emails to all 'scouted' leads with a known contact email.

    Args:
        dry_run: Override Config.DRY_RUN. When True, emails are logged but not sent.

    Returns:
        Number of leads successfully pitched (status updated to 'pitched').
    """
    if dry_run is None:
        dry_run = Config.DRY_RUN

    Config.validate("ANTHROPIC_API_KEY")
    if not dry_run:
        Config.validate("RESEND_API_KEY")
        resend.api_key = Config.RESEND_API_KEY

    if dry_run:
        log.info("DRY RUN mode — emails will be drafted and logged but NOT delivered.")
    else:
        log.info("LIVE mode — emails will be sent via Resend.")

    claude = anthropic.Anthropic(api_key=Config.ANTHROPIC_API_KEY)

    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT id, company_name, url, contact_email, context_notes "
        "FROM companies WHERE status = 'scouted'"
    )
    leads = cursor.fetchall()

    if not leads:
        log.info("No 'scouted' leads found. Run scout first.")
        conn.close()
        return 0

    log.info(f"Processing {len(leads)} scouted lead(s).")
    pitched = 0

    for lead in leads:
        lead_id = lead["id"]
        company_name = lead["company_name"]
        url = lead["url"]
        contact_email = lead["contact_email"]
        context_notes = lead["context_notes"] or ""

        if not contact_email:
            log.warning(f"Skipping '{company_name}': no contact email on file.")
            continue

        log.info(f"Drafting email for '{company_name}' → {contact_email}")
        subject, body = _draft_email(claude, company_name, url, context_notes)

        log.info(f"  Subject: {subject}")
        log.debug(f"  Body:\n{body}")

        if not dry_run:
            try:
                resend.Emails.send({
                    "from": f"{Config.SENDER_NAME} <{Config.SENDER_EMAIL}>",
                    "to": [contact_email],
                    "subject": subject,
                    "text": body,
                })
                log.info(f"  Sent to {contact_email}.")
            except Exception as e:
                log.error(f"  Resend delivery failed for {contact_email}: {e}")
                continue  # Don't mark as pitched if delivery failed
        else:
            log.info(f"  [DRY RUN] Would send to {contact_email}.")

        cursor.execute(
            """
            UPDATE companies
            SET status        = 'pitched',
                email_subject = ?,
                email_body    = ?,
                pitched_at    = datetime('now'),
                updated_at    = datetime('now')
            WHERE id = ?
            """,
            (subject, body, lead_id),
        )
        conn.commit()
        pitched += 1
        log.info(f"  Marked '{company_name}' as 'pitched'.")

        # Rate limiting — be a good API citizen
        if pitched < len(leads):
            time.sleep(Config.EMAIL_RATE_LIMIT_SECONDS)

    conn.close()
    log.info(f"Negotiation complete. {pitched} lead(s) pitched.")
    return pitched


if __name__ == "__main__":
    draft_and_send_emails()
